version: '3'

services:
  rabbitmqstats:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=foo
      - RABBITMQ_PASSWORD=bar
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmqstats
      - RABBITMQ_CLUSTER_PARTITION_HANDLING=pause_minority
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_DISK_FREE_LIMIT=1000000000
    ports:
      - '15673:15672'
    #  - '5672:5672'
    volumes:
      - 'rabbitmqstats_data:/bitnami'
    networks:
      rabbit_net:
        aliases:
          - rabbitmqstats

  rabbitmq1:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmqstats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_DISK_FREE_LIMIT=1000000000
    volumes:
      - 'rabbitmq1_data:/bitnami'
    networks:
      rabbit_net:
        aliases:
          - rabbitmq1

  rabbitmq2:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq2
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@rabbitmqstats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_DISK_FREE_LIMIT=1000000000
    volumes:
      - 'rabbitmq2_data:/bitnami'
    networks:
      rabbit_net:
        aliases:
          - rabbitmq2

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - rabbit_net
    depends_on:
      - rabbitmqstats
      - rabbitmq1
      - rabbitmq2
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936

volumes:
  rabbitmqstats_data:
    driver: local
  rabbitmq1_data:
    driver: local
  rabbitmq2_data:
    driver: local

networks:
  rabbit_net:
    external:
      name: rabbit_net
